# Generated by Django 6.0 on 2025-12-23 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_question_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 30, 18, 29, 37, 733162, tzinfo=datetime.timezone.utc), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/ez.jpg', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
